// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moderator.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Moderator_Fee_FeeType int32

const (
	Moderator_Fee_FIXED                 Moderator_Fee_FeeType = 0
	Moderator_Fee_PERCENTAGE            Moderator_Fee_FeeType = 1
	Moderator_Fee_FIXED_PLUS_PERCENTAGE Moderator_Fee_FeeType = 2
)

var Moderator_Fee_FeeType_name = map[int32]string{
	0: "FIXED",
	1: "PERCENTAGE",
	2: "FIXED_PLUS_PERCENTAGE",
}

var Moderator_Fee_FeeType_value = map[string]int32{
	"FIXED":                 0,
	"PERCENTAGE":            1,
	"FIXED_PLUS_PERCENTAGE": 2,
}

func (x Moderator_Fee_FeeType) String() string {
	return proto.EnumName(Moderator_Fee_FeeType_name, int32(x))
}

func (Moderator_Fee_FeeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44f20453d9230215, []int{0, 0, 0}
}

type Moderator struct {
	Description          string         `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	TermsAndConditions   string         `protobuf:"bytes,2,opt,name=termsAndConditions,proto3" json:"termsAndConditions,omitempty"`
	Languages            []string       `protobuf:"bytes,3,rep,name=languages,proto3" json:"languages,omitempty"`
	AcceptedCurrencies   []string       `protobuf:"bytes,4,rep,name=acceptedCurrencies,proto3" json:"acceptedCurrencies,omitempty"`
	Fee                  *Moderator_Fee `protobuf:"bytes,5,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Moderator) Reset()         { *m = Moderator{} }
func (m *Moderator) String() string { return proto.CompactTextString(m) }
func (*Moderator) ProtoMessage()    {}
func (*Moderator) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f20453d9230215, []int{0}
}

func (m *Moderator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Moderator.Unmarshal(m, b)
}
func (m *Moderator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Moderator.Marshal(b, m, deterministic)
}
func (m *Moderator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Moderator.Merge(m, src)
}
func (m *Moderator) XXX_Size() int {
	return xxx_messageInfo_Moderator.Size(m)
}
func (m *Moderator) XXX_DiscardUnknown() {
	xxx_messageInfo_Moderator.DiscardUnknown(m)
}

var xxx_messageInfo_Moderator proto.InternalMessageInfo

func (m *Moderator) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Moderator) GetTermsAndConditions() string {
	if m != nil {
		return m.TermsAndConditions
	}
	return ""
}

func (m *Moderator) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *Moderator) GetAcceptedCurrencies() []string {
	if m != nil {
		return m.AcceptedCurrencies
	}
	return nil
}

func (m *Moderator) GetFee() *Moderator_Fee {
	if m != nil {
		return m.Fee
	}
	return nil
}

type Moderator_Fee struct {
	FixedFee             *Moderator_Price      `protobuf:"bytes,1,opt,name=fixedFee,proto3" json:"fixedFee,omitempty"`
	Percentage           float32               `protobuf:"fixed32,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	FeeType              Moderator_Fee_FeeType `protobuf:"varint,3,opt,name=feeType,proto3,enum=Moderator_Fee_FeeType" json:"feeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Moderator_Fee) Reset()         { *m = Moderator_Fee{} }
func (m *Moderator_Fee) String() string { return proto.CompactTextString(m) }
func (*Moderator_Fee) ProtoMessage()    {}
func (*Moderator_Fee) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f20453d9230215, []int{0, 0}
}

func (m *Moderator_Fee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Moderator_Fee.Unmarshal(m, b)
}
func (m *Moderator_Fee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Moderator_Fee.Marshal(b, m, deterministic)
}
func (m *Moderator_Fee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Moderator_Fee.Merge(m, src)
}
func (m *Moderator_Fee) XXX_Size() int {
	return xxx_messageInfo_Moderator_Fee.Size(m)
}
func (m *Moderator_Fee) XXX_DiscardUnknown() {
	xxx_messageInfo_Moderator_Fee.DiscardUnknown(m)
}

var xxx_messageInfo_Moderator_Fee proto.InternalMessageInfo

func (m *Moderator_Fee) GetFixedFee() *Moderator_Price {
	if m != nil {
		return m.FixedFee
	}
	return nil
}

func (m *Moderator_Fee) GetPercentage() float32 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func (m *Moderator_Fee) GetFeeType() Moderator_Fee_FeeType {
	if m != nil {
		return m.FeeType
	}
	return Moderator_Fee_FIXED
}

type Moderator_Price struct {
	CurrencyCode         string   `protobuf:"bytes,1,opt,name=currencyCode,proto3" json:"currencyCode,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Moderator_Price) Reset()         { *m = Moderator_Price{} }
func (m *Moderator_Price) String() string { return proto.CompactTextString(m) }
func (*Moderator_Price) ProtoMessage()    {}
func (*Moderator_Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f20453d9230215, []int{0, 1}
}

func (m *Moderator_Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Moderator_Price.Unmarshal(m, b)
}
func (m *Moderator_Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Moderator_Price.Marshal(b, m, deterministic)
}
func (m *Moderator_Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Moderator_Price.Merge(m, src)
}
func (m *Moderator_Price) XXX_Size() int {
	return xxx_messageInfo_Moderator_Price.Size(m)
}
func (m *Moderator_Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Moderator_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Moderator_Price proto.InternalMessageInfo

func (m *Moderator_Price) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *Moderator_Price) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type DisputeUpdate struct {
	OrderId              string      `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	PayoutAddress        string      `protobuf:"bytes,2,opt,name=payoutAddress,proto3" json:"payoutAddress,omitempty"`
	Outpoints            []*Outpoint `protobuf:"bytes,3,rep,name=outpoints,proto3" json:"outpoints,omitempty"`
	SerializedContract   []byte      `protobuf:"bytes,4,opt,name=serializedContract,proto3" json:"serializedContract,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DisputeUpdate) Reset()         { *m = DisputeUpdate{} }
func (m *DisputeUpdate) String() string { return proto.CompactTextString(m) }
func (*DisputeUpdate) ProtoMessage()    {}
func (*DisputeUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_44f20453d9230215, []int{1}
}

func (m *DisputeUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisputeUpdate.Unmarshal(m, b)
}
func (m *DisputeUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisputeUpdate.Marshal(b, m, deterministic)
}
func (m *DisputeUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisputeUpdate.Merge(m, src)
}
func (m *DisputeUpdate) XXX_Size() int {
	return xxx_messageInfo_DisputeUpdate.Size(m)
}
func (m *DisputeUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_DisputeUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_DisputeUpdate proto.InternalMessageInfo

func (m *DisputeUpdate) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *DisputeUpdate) GetPayoutAddress() string {
	if m != nil {
		return m.PayoutAddress
	}
	return ""
}

func (m *DisputeUpdate) GetOutpoints() []*Outpoint {
	if m != nil {
		return m.Outpoints
	}
	return nil
}

func (m *DisputeUpdate) GetSerializedContract() []byte {
	if m != nil {
		return m.SerializedContract
	}
	return nil
}

func init() {
	proto.RegisterEnum("Moderator_Fee_FeeType", Moderator_Fee_FeeType_name, Moderator_Fee_FeeType_value)
	proto.RegisterType((*Moderator)(nil), "Moderator")
	proto.RegisterType((*Moderator_Fee)(nil), "Moderator.Fee")
	proto.RegisterType((*Moderator_Price)(nil), "Moderator.Price")
	proto.RegisterType((*DisputeUpdate)(nil), "DisputeUpdate")
}

func init() { proto.RegisterFile("moderator.proto", fileDescriptor_44f20453d9230215) }

var fileDescriptor_44f20453d9230215 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x52, 0x6d, 0x6a, 0x1b, 0x31,
	0x10, 0xed, 0x7a, 0xed, 0xb8, 0x3b, 0x4e, 0x1c, 0x23, 0x68, 0xd8, 0x9a, 0x52, 0x8c, 0x29, 0xd4,
	0x3f, 0xca, 0x52, 0xdc, 0x03, 0x14, 0x77, 0xe3, 0x94, 0x40, 0x3f, 0x8c, 0x9a, 0x40, 0xe9, 0x9f,
	0xa0, 0x48, 0x93, 0x20, 0x88, 0x25, 0x21, 0x69, 0xa1, 0xee, 0x89, 0x7a, 0x92, 0x5e, 0xa2, 0x97,
	0x89, 0x56, 0x5e, 0xc7, 0x36, 0xf8, 0xc7, 0xc2, 0xce, 0x7b, 0x8f, 0x99, 0x37, 0x7a, 0x03, 0xa7,
	0x4b, 0x2d, 0xd0, 0x32, 0xaf, 0x6d, 0x61, 0xac, 0xf6, 0x7a, 0x78, 0xca, 0xb5, 0xf2, 0x96, 0x71,
	0xef, 0xd6, 0xc0, 0xf8, 0x7f, 0x0a, 0xd9, 0xd7, 0x8d, 0x88, 0x8c, 0xa0, 0x27, 0xd0, 0x71, 0x2b,
	0x8d, 0x97, 0x5a, 0xe5, 0xc9, 0x28, 0x99, 0x64, 0x74, 0x17, 0x22, 0x05, 0x10, 0x8f, 0x76, 0xe9,
	0x66, 0x4a, 0x94, 0x5a, 0x09, 0x59, 0x83, 0x2e, 0x6f, 0x45, 0xe1, 0x01, 0x86, 0xbc, 0x82, 0xec,
	0x81, 0xa9, 0xfb, 0x8a, 0xdd, 0xa3, 0xcb, 0xd3, 0x51, 0x1a, 0x64, 0x5b, 0xa0, 0xee, 0xc6, 0x38,
	0x47, 0xe3, 0x51, 0x94, 0x95, 0xb5, 0xa8, 0xb8, 0x0c, 0xb2, 0x76, 0x94, 0x1d, 0x60, 0x82, 0xbf,
	0xf4, 0x0e, 0x31, 0xef, 0x84, 0x71, 0xbd, 0x69, 0xbf, 0x78, 0x32, 0x5e, 0x5c, 0x20, 0xd2, 0x9a,
	0x1a, 0xfe, 0x4b, 0x20, 0x0d, 0x05, 0x79, 0x07, 0xcf, 0xef, 0xe4, 0x6f, 0x14, 0xe1, 0x3f, 0xae,
	0xd1, 0x9b, 0x0e, 0x76, 0xe4, 0x0b, 0x2b, 0x39, 0xd2, 0x27, 0x05, 0x79, 0x0d, 0x60, 0xd0, 0x72,
	0x54, 0x3e, 0xd8, 0x8a, 0xdb, 0xb4, 0xe8, 0x0e, 0x42, 0xde, 0x43, 0x37, 0x34, 0xbf, 0x5a, 0x19,
	0x0c, 0x3b, 0x24, 0x93, 0xfe, 0xf4, 0x6c, 0x7f, 0x76, 0xfd, 0xd5, 0x2c, 0xdd, 0xc8, 0xc6, 0x1f,
	0xa1, 0xdb, 0x60, 0x24, 0x83, 0xce, 0xc5, 0xe5, 0xcf, 0xf9, 0xf9, 0xe0, 0x19, 0xe9, 0x03, 0x2c,
	0xe6, 0xb4, 0x9c, 0x7f, 0xbb, 0x9a, 0x7d, 0x9e, 0x0f, 0x12, 0xf2, 0x12, 0x5e, 0x44, 0xea, 0x66,
	0xf1, 0xe5, 0xfa, 0xc7, 0xcd, 0x0e, 0xd5, 0x1a, 0x96, 0xd0, 0x89, 0x2e, 0xc9, 0x18, 0x8e, 0xf9,
	0xfa, 0x05, 0x56, 0x65, 0x98, 0xd9, 0x84, 0xb2, 0x87, 0x91, 0x33, 0x38, 0x62, 0x4b, 0x5d, 0x29,
	0x1f, 0xbd, 0xb7, 0x69, 0x53, 0x8d, 0xff, 0x26, 0x70, 0x72, 0x2e, 0x9d, 0xa9, 0x3c, 0x5e, 0x1b,
	0xc1, 0x3c, 0x92, 0x1c, 0xba, 0xda, 0x06, 0xe7, 0x97, 0xa2, 0x69, 0xb4, 0x29, 0xc9, 0x1b, 0x38,
	0x31, 0x6c, 0xa5, 0x2b, 0x3f, 0x13, 0xc2, 0xa2, 0xdb, 0x84, 0xba, 0x0f, 0x92, 0xb7, 0x90, 0x85,
	0xca, 0x68, 0xa9, 0xfc, 0x3a, 0xcf, 0xde, 0x34, 0x2b, 0xbe, 0x37, 0x08, 0xdd, 0x72, 0x75, 0xb4,
	0x0e, 0xad, 0x64, 0x0f, 0xf2, 0x0f, 0xd6, 0x07, 0x11, 0xaf, 0x2e, 0x44, 0x9b, 0x4c, 0x8e, 0xe9,
	0x01, 0xe6, 0x53, 0xfb, 0x57, 0xcb, 0xdc, 0xde, 0x1e, 0xc5, 0xab, 0xfc, 0xf0, 0x18, 0x00, 0x00,
	0xff, 0xff, 0x85, 0xeb, 0x32, 0x4a, 0xb9, 0x02, 0x00, 0x00,
}
