// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile struct {
	PeerID               string                 `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	Handle               string                 `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	Name                 string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Location             string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	About                string                 `protobuf:"bytes,5,opt,name=about,proto3" json:"about,omitempty"`
	ShortDescription     string                 `protobuf:"bytes,6,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	Nsfw                 bool                   `protobuf:"varint,7,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	Vendor               bool                   `protobuf:"varint,8,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Moderator            bool                   `protobuf:"varint,9,opt,name=moderator,proto3" json:"moderator,omitempty"`
	ModeratorInfo        *Moderator             `protobuf:"bytes,10,opt,name=moderatorInfo,proto3" json:"moderatorInfo,omitempty"`
	ContactInfo          *Profile_Contact       `protobuf:"bytes,11,opt,name=contactInfo,proto3" json:"contactInfo,omitempty"`
	Colors               *Profile_Colors        `protobuf:"bytes,12,opt,name=colors,proto3" json:"colors,omitempty"`
	AvatarHashes         *Profile_Image         `protobuf:"bytes,13,opt,name=avatarHashes,proto3" json:"avatarHashes,omitempty"`
	HeaderHashes         *Profile_Image         `protobuf:"bytes,14,opt,name=headerHashes,proto3" json:"headerHashes,omitempty"`
	Stats                *Profile_Stats         `protobuf:"bytes,15,opt,name=stats,proto3" json:"stats,omitempty"`
	BitcoinPubkey        string                 `protobuf:"bytes,16,opt,name=bitcoinPubkey,proto3" json:"bitcoinPubkey,omitempty"`
	LastModified         *timestamp.Timestamp   `protobuf:"bytes,17,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	Currencies           []string               `protobuf:"bytes,18,rep,name=currencies,proto3" json:"currencies,omitempty"`
	ExtLocation          *ExtLocation           `protobuf:"bytes,6660,opt,name=extLocation,proto3" json:"extLocation,omitempty"`
	Background           *Profile_Background    `protobuf:"bytes,6661,opt,name=background,proto3" json:"background,omitempty"`
	ProfileType          string                 `protobuf:"bytes,6662,opt,name=profileType,proto3" json:"profileType,omitempty"`
	MetaTags             map[string]string      `protobuf:"bytes,6663,rep,name=metaTags,proto3" json:"metaTags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Preferences          *Profile_Preferences   `protobuf:"bytes,6664,opt,name=preferences,proto3" json:"preferences,omitempty"`
	CustomFields         []*Profile_CustomField `protobuf:"bytes,6665,rep,name=customFields,proto3" json:"customFields,omitempty"`
	CustomProps          map[string]string      `protobuf:"bytes,6666,rep,name=customProps,proto3" json:"customProps,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *Profile) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Profile) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *Profile) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *Profile) GetNsfw() bool {
	if m != nil {
		return m.Nsfw
	}
	return false
}

func (m *Profile) GetVendor() bool {
	if m != nil {
		return m.Vendor
	}
	return false
}

func (m *Profile) GetModerator() bool {
	if m != nil {
		return m.Moderator
	}
	return false
}

func (m *Profile) GetModeratorInfo() *Moderator {
	if m != nil {
		return m.ModeratorInfo
	}
	return nil
}

func (m *Profile) GetContactInfo() *Profile_Contact {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

func (m *Profile) GetColors() *Profile_Colors {
	if m != nil {
		return m.Colors
	}
	return nil
}

func (m *Profile) GetAvatarHashes() *Profile_Image {
	if m != nil {
		return m.AvatarHashes
	}
	return nil
}

func (m *Profile) GetHeaderHashes() *Profile_Image {
	if m != nil {
		return m.HeaderHashes
	}
	return nil
}

func (m *Profile) GetStats() *Profile_Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Profile) GetBitcoinPubkey() string {
	if m != nil {
		return m.BitcoinPubkey
	}
	return ""
}

func (m *Profile) GetLastModified() *timestamp.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

func (m *Profile) GetCurrencies() []string {
	if m != nil {
		return m.Currencies
	}
	return nil
}

func (m *Profile) GetExtLocation() *ExtLocation {
	if m != nil {
		return m.ExtLocation
	}
	return nil
}

func (m *Profile) GetBackground() *Profile_Background {
	if m != nil {
		return m.Background
	}
	return nil
}

func (m *Profile) GetProfileType() string {
	if m != nil {
		return m.ProfileType
	}
	return ""
}

func (m *Profile) GetMetaTags() map[string]string {
	if m != nil {
		return m.MetaTags
	}
	return nil
}

func (m *Profile) GetPreferences() *Profile_Preferences {
	if m != nil {
		return m.Preferences
	}
	return nil
}

func (m *Profile) GetCustomFields() []*Profile_CustomField {
	if m != nil {
		return m.CustomFields
	}
	return nil
}

func (m *Profile) GetCustomProps() map[string]string {
	if m != nil {
		return m.CustomProps
	}
	return nil
}

type Profile_CustomField struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_CustomField) Reset()         { *m = Profile_CustomField{} }
func (m *Profile_CustomField) String() string { return proto.CompactTextString(m) }
func (*Profile_CustomField) ProtoMessage()    {}
func (*Profile_CustomField) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 2}
}

func (m *Profile_CustomField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_CustomField.Unmarshal(m, b)
}
func (m *Profile_CustomField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_CustomField.Marshal(b, m, deterministic)
}
func (m *Profile_CustomField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_CustomField.Merge(m, src)
}
func (m *Profile_CustomField) XXX_Size() int {
	return xxx_messageInfo_Profile_CustomField.Size(m)
}
func (m *Profile_CustomField) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_CustomField.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_CustomField proto.InternalMessageInfo

func (m *Profile_CustomField) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Profile_CustomField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Profile_Preferences struct {
	CurrencyDisplay      string   `protobuf:"bytes,1,opt,name=currencyDisplay,proto3" json:"currencyDisplay,omitempty"`
	Fiat                 string   `protobuf:"bytes,2,opt,name=fiat,proto3" json:"fiat,omitempty"`
	Cryptocurrency       string   `protobuf:"bytes,3,opt,name=cryptocurrency,proto3" json:"cryptocurrency,omitempty"`
	Language             string   `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	MeasurementUnit      string   `protobuf:"bytes,5,opt,name=measurementUnit,proto3" json:"measurementUnit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_Preferences) Reset()         { *m = Profile_Preferences{} }
func (m *Profile_Preferences) String() string { return proto.CompactTextString(m) }
func (*Profile_Preferences) ProtoMessage()    {}
func (*Profile_Preferences) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 3}
}

func (m *Profile_Preferences) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Preferences.Unmarshal(m, b)
}
func (m *Profile_Preferences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Preferences.Marshal(b, m, deterministic)
}
func (m *Profile_Preferences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Preferences.Merge(m, src)
}
func (m *Profile_Preferences) XXX_Size() int {
	return xxx_messageInfo_Profile_Preferences.Size(m)
}
func (m *Profile_Preferences) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Preferences.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Preferences proto.InternalMessageInfo

func (m *Profile_Preferences) GetCurrencyDisplay() string {
	if m != nil {
		return m.CurrencyDisplay
	}
	return ""
}

func (m *Profile_Preferences) GetFiat() string {
	if m != nil {
		return m.Fiat
	}
	return ""
}

func (m *Profile_Preferences) GetCryptocurrency() string {
	if m != nil {
		return m.Cryptocurrency
	}
	return ""
}

func (m *Profile_Preferences) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Profile_Preferences) GetMeasurementUnit() string {
	if m != nil {
		return m.MeasurementUnit
	}
	return ""
}

type Profile_Background struct {
	EducationHistory     []*Profile_Background_EducationHistory  `protobuf:"bytes,1,rep,name=educationHistory,proto3" json:"educationHistory,omitempty"`
	EmploymentHistory    []*Profile_Background_EmploymentHistory `protobuf:"bytes,2,rep,name=employmentHistory,proto3" json:"employmentHistory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *Profile_Background) Reset()         { *m = Profile_Background{} }
func (m *Profile_Background) String() string { return proto.CompactTextString(m) }
func (*Profile_Background) ProtoMessage()    {}
func (*Profile_Background) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 4}
}

func (m *Profile_Background) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Background.Unmarshal(m, b)
}
func (m *Profile_Background) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Background.Marshal(b, m, deterministic)
}
func (m *Profile_Background) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Background.Merge(m, src)
}
func (m *Profile_Background) XXX_Size() int {
	return xxx_messageInfo_Profile_Background.Size(m)
}
func (m *Profile_Background) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Background.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Background proto.InternalMessageInfo

func (m *Profile_Background) GetEducationHistory() []*Profile_Background_EducationHistory {
	if m != nil {
		return m.EducationHistory
	}
	return nil
}

func (m *Profile_Background) GetEmploymentHistory() []*Profile_Background_EmploymentHistory {
	if m != nil {
		return m.EmploymentHistory
	}
	return nil
}

type Profile_Background_EducationHistory struct {
	School               string            `protobuf:"bytes,1,opt,name=school,proto3" json:"school,omitempty"`
	Period               *Profile_Timespan `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	Degree               string            `protobuf:"bytes,3,opt,name=degree,proto3" json:"degree,omitempty"`
	Description          string            `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Profile_Background_EducationHistory) Reset()         { *m = Profile_Background_EducationHistory{} }
func (m *Profile_Background_EducationHistory) String() string { return proto.CompactTextString(m) }
func (*Profile_Background_EducationHistory) ProtoMessage()    {}
func (*Profile_Background_EducationHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 4, 0}
}

func (m *Profile_Background_EducationHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Background_EducationHistory.Unmarshal(m, b)
}
func (m *Profile_Background_EducationHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Background_EducationHistory.Marshal(b, m, deterministic)
}
func (m *Profile_Background_EducationHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Background_EducationHistory.Merge(m, src)
}
func (m *Profile_Background_EducationHistory) XXX_Size() int {
	return xxx_messageInfo_Profile_Background_EducationHistory.Size(m)
}
func (m *Profile_Background_EducationHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Background_EducationHistory.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Background_EducationHistory proto.InternalMessageInfo

func (m *Profile_Background_EducationHistory) GetSchool() string {
	if m != nil {
		return m.School
	}
	return ""
}

func (m *Profile_Background_EducationHistory) GetPeriod() *Profile_Timespan {
	if m != nil {
		return m.Period
	}
	return nil
}

func (m *Profile_Background_EducationHistory) GetDegree() string {
	if m != nil {
		return m.Degree
	}
	return ""
}

func (m *Profile_Background_EducationHistory) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Profile_Background_EmploymentHistory struct {
	Company              string            `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Description          string            `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Location             *Profile_Location `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Title                string            `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Role                 string            `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Period               *Profile_Timespan `protobuf:"bytes,6,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Profile_Background_EmploymentHistory) Reset()         { *m = Profile_Background_EmploymentHistory{} }
func (m *Profile_Background_EmploymentHistory) String() string { return proto.CompactTextString(m) }
func (*Profile_Background_EmploymentHistory) ProtoMessage()    {}
func (*Profile_Background_EmploymentHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 4, 1}
}

func (m *Profile_Background_EmploymentHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Background_EmploymentHistory.Unmarshal(m, b)
}
func (m *Profile_Background_EmploymentHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Background_EmploymentHistory.Marshal(b, m, deterministic)
}
func (m *Profile_Background_EmploymentHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Background_EmploymentHistory.Merge(m, src)
}
func (m *Profile_Background_EmploymentHistory) XXX_Size() int {
	return xxx_messageInfo_Profile_Background_EmploymentHistory.Size(m)
}
func (m *Profile_Background_EmploymentHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Background_EmploymentHistory.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Background_EmploymentHistory proto.InternalMessageInfo

func (m *Profile_Background_EmploymentHistory) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Profile_Background_EmploymentHistory) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Profile_Background_EmploymentHistory) GetLocation() *Profile_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Profile_Background_EmploymentHistory) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Profile_Background_EmploymentHistory) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Profile_Background_EmploymentHistory) GetPeriod() *Profile_Timespan {
	if m != nil {
		return m.Period
	}
	return nil
}

type Profile_Timespan struct {
	From                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Profile_Timespan) Reset()         { *m = Profile_Timespan{} }
func (m *Profile_Timespan) String() string { return proto.CompactTextString(m) }
func (*Profile_Timespan) ProtoMessage()    {}
func (*Profile_Timespan) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 5}
}

func (m *Profile_Timespan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Timespan.Unmarshal(m, b)
}
func (m *Profile_Timespan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Timespan.Marshal(b, m, deterministic)
}
func (m *Profile_Timespan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Timespan.Merge(m, src)
}
func (m *Profile_Timespan) XXX_Size() int {
	return xxx_messageInfo_Profile_Timespan.Size(m)
}
func (m *Profile_Timespan) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Timespan.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Timespan proto.InternalMessageInfo

func (m *Profile_Timespan) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Profile_Timespan) GetTo() *timestamp.Timestamp {
	if m != nil {
		return m.To
	}
	return nil
}

type Profile_Location struct {
	City                 string   `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_Location) Reset()         { *m = Profile_Location{} }
func (m *Profile_Location) String() string { return proto.CompactTextString(m) }
func (*Profile_Location) ProtoMessage()    {}
func (*Profile_Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 6}
}

func (m *Profile_Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Location.Unmarshal(m, b)
}
func (m *Profile_Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Location.Marshal(b, m, deterministic)
}
func (m *Profile_Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Location.Merge(m, src)
}
func (m *Profile_Location) XXX_Size() int {
	return xxx_messageInfo_Profile_Location.Size(m)
}
func (m *Profile_Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Location proto.InternalMessageInfo

func (m *Profile_Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Profile_Location) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type Profile_Contact struct {
	Website              string                   `protobuf:"bytes,1,opt,name=website,proto3" json:"website,omitempty"`
	Email                string                   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string                   `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Social               []*Profile_SocialAccount `protobuf:"bytes,4,rep,name=social,proto3" json:"social,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Profile_Contact) Reset()         { *m = Profile_Contact{} }
func (m *Profile_Contact) String() string { return proto.CompactTextString(m) }
func (*Profile_Contact) ProtoMessage()    {}
func (*Profile_Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 7}
}

func (m *Profile_Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Contact.Unmarshal(m, b)
}
func (m *Profile_Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Contact.Marshal(b, m, deterministic)
}
func (m *Profile_Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Contact.Merge(m, src)
}
func (m *Profile_Contact) XXX_Size() int {
	return xxx_messageInfo_Profile_Contact.Size(m)
}
func (m *Profile_Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Contact proto.InternalMessageInfo

func (m *Profile_Contact) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Profile_Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Profile_Contact) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Profile_Contact) GetSocial() []*Profile_SocialAccount {
	if m != nil {
		return m.Social
	}
	return nil
}

type Profile_SocialAccount struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Proof                string   `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_SocialAccount) Reset()         { *m = Profile_SocialAccount{} }
func (m *Profile_SocialAccount) String() string { return proto.CompactTextString(m) }
func (*Profile_SocialAccount) ProtoMessage()    {}
func (*Profile_SocialAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 8}
}

func (m *Profile_SocialAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_SocialAccount.Unmarshal(m, b)
}
func (m *Profile_SocialAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_SocialAccount.Marshal(b, m, deterministic)
}
func (m *Profile_SocialAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_SocialAccount.Merge(m, src)
}
func (m *Profile_SocialAccount) XXX_Size() int {
	return xxx_messageInfo_Profile_SocialAccount.Size(m)
}
func (m *Profile_SocialAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_SocialAccount.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_SocialAccount proto.InternalMessageInfo

func (m *Profile_SocialAccount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Profile_SocialAccount) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Profile_SocialAccount) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

type Profile_Image struct {
	Tiny                 string   `protobuf:"bytes,1,opt,name=tiny,proto3" json:"tiny,omitempty"`
	Small                string   `protobuf:"bytes,2,opt,name=small,proto3" json:"small,omitempty"`
	Medium               string   `protobuf:"bytes,3,opt,name=medium,proto3" json:"medium,omitempty"`
	Large                string   `protobuf:"bytes,4,opt,name=large,proto3" json:"large,omitempty"`
	Original             string   `protobuf:"bytes,5,opt,name=original,proto3" json:"original,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_Image) Reset()         { *m = Profile_Image{} }
func (m *Profile_Image) String() string { return proto.CompactTextString(m) }
func (*Profile_Image) ProtoMessage()    {}
func (*Profile_Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 9}
}

func (m *Profile_Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Image.Unmarshal(m, b)
}
func (m *Profile_Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Image.Marshal(b, m, deterministic)
}
func (m *Profile_Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Image.Merge(m, src)
}
func (m *Profile_Image) XXX_Size() int {
	return xxx_messageInfo_Profile_Image.Size(m)
}
func (m *Profile_Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Image proto.InternalMessageInfo

func (m *Profile_Image) GetTiny() string {
	if m != nil {
		return m.Tiny
	}
	return ""
}

func (m *Profile_Image) GetSmall() string {
	if m != nil {
		return m.Small
	}
	return ""
}

func (m *Profile_Image) GetMedium() string {
	if m != nil {
		return m.Medium
	}
	return ""
}

func (m *Profile_Image) GetLarge() string {
	if m != nil {
		return m.Large
	}
	return ""
}

func (m *Profile_Image) GetOriginal() string {
	if m != nil {
		return m.Original
	}
	return ""
}

type Profile_Colors struct {
	Primary              string   `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondary            string   `protobuf:"bytes,2,opt,name=secondary,proto3" json:"secondary,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Highlight            string   `protobuf:"bytes,4,opt,name=highlight,proto3" json:"highlight,omitempty"`
	HighlightText        string   `protobuf:"bytes,5,opt,name=highlightText,proto3" json:"highlightText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_Colors) Reset()         { *m = Profile_Colors{} }
func (m *Profile_Colors) String() string { return proto.CompactTextString(m) }
func (*Profile_Colors) ProtoMessage()    {}
func (*Profile_Colors) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 10}
}

func (m *Profile_Colors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Colors.Unmarshal(m, b)
}
func (m *Profile_Colors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Colors.Marshal(b, m, deterministic)
}
func (m *Profile_Colors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Colors.Merge(m, src)
}
func (m *Profile_Colors) XXX_Size() int {
	return xxx_messageInfo_Profile_Colors.Size(m)
}
func (m *Profile_Colors) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Colors.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Colors proto.InternalMessageInfo

func (m *Profile_Colors) GetPrimary() string {
	if m != nil {
		return m.Primary
	}
	return ""
}

func (m *Profile_Colors) GetSecondary() string {
	if m != nil {
		return m.Secondary
	}
	return ""
}

func (m *Profile_Colors) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Profile_Colors) GetHighlight() string {
	if m != nil {
		return m.Highlight
	}
	return ""
}

func (m *Profile_Colors) GetHighlightText() string {
	if m != nil {
		return m.HighlightText
	}
	return ""
}

type Profile_Stats struct {
	FollowerCount        uint32   `protobuf:"varint,1,opt,name=followerCount,proto3" json:"followerCount,omitempty"`
	FollowingCount       uint32   `protobuf:"varint,2,opt,name=followingCount,proto3" json:"followingCount,omitempty"`
	ListingCount         uint32   `protobuf:"varint,3,opt,name=listingCount,proto3" json:"listingCount,omitempty"`
	RatingCount          uint32   `protobuf:"varint,4,opt,name=ratingCount,proto3" json:"ratingCount,omitempty"`
	PostCount            uint32   `protobuf:"varint,5,opt,name=postCount,proto3" json:"postCount,omitempty"`
	AverageRating        float32  `protobuf:"fixed32,6,opt,name=averageRating,proto3" json:"averageRating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_Stats) Reset()         { *m = Profile_Stats{} }
func (m *Profile_Stats) String() string { return proto.CompactTextString(m) }
func (*Profile_Stats) ProtoMessage()    {}
func (*Profile_Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 11}
}

func (m *Profile_Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Stats.Unmarshal(m, b)
}
func (m *Profile_Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Stats.Marshal(b, m, deterministic)
}
func (m *Profile_Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Stats.Merge(m, src)
}
func (m *Profile_Stats) XXX_Size() int {
	return xxx_messageInfo_Profile_Stats.Size(m)
}
func (m *Profile_Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Stats proto.InternalMessageInfo

func (m *Profile_Stats) GetFollowerCount() uint32 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *Profile_Stats) GetFollowingCount() uint32 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *Profile_Stats) GetListingCount() uint32 {
	if m != nil {
		return m.ListingCount
	}
	return 0
}

func (m *Profile_Stats) GetRatingCount() uint32 {
	if m != nil {
		return m.RatingCount
	}
	return 0
}

func (m *Profile_Stats) GetPostCount() uint32 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *Profile_Stats) GetAverageRating() float32 {
	if m != nil {
		return m.AverageRating
	}
	return 0
}

func init() {
	proto.RegisterType((*Profile)(nil), "Profile")
	proto.RegisterMapType((map[string]string)(nil), "Profile.CustomPropsEntry")
	proto.RegisterMapType((map[string]string)(nil), "Profile.MetaTagsEntry")
	proto.RegisterType((*Profile_CustomField)(nil), "Profile.CustomField")
	proto.RegisterType((*Profile_Preferences)(nil), "Profile.Preferences")
	proto.RegisterType((*Profile_Background)(nil), "Profile.Background")
	proto.RegisterType((*Profile_Background_EducationHistory)(nil), "Profile.Background.EducationHistory")
	proto.RegisterType((*Profile_Background_EmploymentHistory)(nil), "Profile.Background.EmploymentHistory")
	proto.RegisterType((*Profile_Timespan)(nil), "Profile.Timespan")
	proto.RegisterType((*Profile_Location)(nil), "Profile.Location")
	proto.RegisterType((*Profile_Contact)(nil), "Profile.Contact")
	proto.RegisterType((*Profile_SocialAccount)(nil), "Profile.SocialAccount")
	proto.RegisterType((*Profile_Image)(nil), "Profile.Image")
	proto.RegisterType((*Profile_Colors)(nil), "Profile.Colors")
	proto.RegisterType((*Profile_Stats)(nil), "Profile.Stats")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 1215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x56, 0x5f, 0x6f, 0x23, 0x35,
	0x10, 0x57, 0xd2, 0x26, 0x4d, 0x9d, 0xa6, 0x4d, 0xcd, 0xa9, 0x2c, 0x2b, 0x04, 0xe5, 0x74, 0xc0,
	0x81, 0x44, 0x8a, 0x7a, 0x95, 0xb8, 0x03, 0x74, 0x12, 0xd7, 0x16, 0x5d, 0x25, 0x0e, 0x55, 0xdb,
	0xde, 0x0b, 0x2f, 0xc8, 0xd9, 0x75, 0x12, 0xeb, 0x76, 0xd7, 0x2b, 0xaf, 0xb7, 0x25, 0xe2, 0x95,
	0xff, 0x3c, 0xf0, 0x8a, 0x04, 0x5f, 0x84, 0xcf, 0xc1, 0x07, 0xe0, 0xab, 0x60, 0x8f, 0xff, 0x64,
	0x77, 0x5b, 0x1d, 0xe2, 0x21, 0x8a, 0xe7, 0x37, 0xbf, 0x99, 0x9d, 0x19, 0x8f, 0xc7, 0x46, 0xa3,
	0x42, 0xf0, 0x19, 0x4b, 0xe9, 0x44, 0xfd, 0x4b, 0x1e, 0xbe, 0x39, 0xe7, 0x7c, 0x9e, 0xd2, 0x03,
	0x90, 0xa6, 0xd5, 0xec, 0x40, 0xb2, 0x8c, 0x96, 0x92, 0x64, 0x85, 0x25, 0xec, 0x64, 0x3c, 0xa1,
	0x82, 0x48, 0x2e, 0x2c, 0xf0, 0x2a, 0xfd, 0x46, 0xd2, 0x3c, 0xa1, 0xc9, 0xd7, 0x29, 0x8f, 0x89,
	0x64, 0x3c, 0x37, 0x8a, 0xbb, 0x7f, 0xee, 0xa1, 0x8d, 0x73, 0xe3, 0x1c, 0xef, 0xa1, 0x7e, 0x41,
	0xa9, 0x38, 0x3b, 0x09, 0x3a, 0xfb, 0x9d, 0xfb, 0x9b, 0x91, 0x95, 0x34, 0xbe, 0x20, 0x79, 0x92,
	0xd2, 0xa0, 0x6b, 0x70, 0x23, 0x61, 0x8c, 0xd6, 0x73, 0x92, 0xd1, 0x60, 0x0d, 0x50, 0x58, 0xe3,
	0x10, 0x0d, 0xdc, 0x17, 0x82, 0x75, 0xc0, 0xbd, 0x8c, 0xef, 0xa0, 0x1e, 0x99, 0xf2, 0x4a, 0x06,
	0x3d, 0x50, 0x18, 0x01, 0xbf, 0x8f, 0xc6, 0xe5, 0x82, 0x0b, 0x79, 0x42, 0xcb, 0x58, 0xb0, 0x02,
	0x2c, 0xfb, 0x40, 0xb8, 0x81, 0xc3, 0x17, 0xcb, 0xd9, 0x75, 0xb0, 0xa1, 0xf4, 0x83, 0x08, 0xd6,
	0x3a, 0xba, 0x2b, 0x95, 0x1a, 0x17, 0xc1, 0x00, 0x50, 0x2b, 0xe1, 0xd7, 0xd1, 0xa6, 0xaf, 0x42,
	0xb0, 0x09, 0xaa, 0x15, 0x80, 0x3f, 0x44, 0x23, 0x2f, 0x9c, 0xe5, 0x33, 0x1e, 0x20, 0xc5, 0x18,
	0x1e, 0xa2, 0xc9, 0x33, 0x87, 0x46, 0x4d, 0x02, 0x3e, 0x44, 0xc3, 0x98, 0xe7, 0x92, 0xc4, 0x12,
	0xf8, 0x43, 0xe0, 0x8f, 0x27, 0xb6, 0x78, 0x93, 0x63, 0xa3, 0x8b, 0xea, 0x24, 0xfc, 0x2e, 0xea,
	0xc7, 0x3c, 0xe5, 0xa2, 0x0c, 0xb6, 0x80, 0xbe, 0x53, 0xa3, 0x6b, 0x38, 0xb2, 0x6a, 0xe5, 0x7c,
	0x8b, 0x5c, 0x11, 0x49, 0xc4, 0x53, 0x52, 0x2e, 0x68, 0x19, 0x8c, 0x80, 0xbe, 0xed, 0xe9, 0x67,
	0x19, 0x99, 0xd3, 0xa8, 0xc1, 0xd1, 0x36, 0x0b, 0x4a, 0x54, 0x88, 0xd6, 0x66, 0xfb, 0x76, 0x9b,
	0x3a, 0x07, 0xdf, 0x43, 0x3d, 0xd5, 0x27, 0xb2, 0x0c, 0x76, 0x5a, 0xe4, 0x0b, 0x8d, 0x46, 0x46,
	0xa9, 0x58, 0xa3, 0x29, 0x93, 0x31, 0x67, 0xf9, 0x79, 0x35, 0x7d, 0x41, 0x97, 0xc1, 0x18, 0xf6,
	0xa3, 0x09, 0xe2, 0xc7, 0x68, 0x2b, 0x25, 0xa5, 0x54, 0x05, 0x63, 0x33, 0x46, 0x93, 0x60, 0x17,
	0x5c, 0x86, 0x13, 0xd3, 0x9c, 0x13, 0xd7, 0x9c, 0x93, 0x4b, 0xd7, 0x9c, 0x51, 0x83, 0x8f, 0xdf,
	0x40, 0x28, 0xae, 0x84, 0xa0, 0x79, 0xcc, 0x54, 0xf4, 0x78, 0x7f, 0x4d, 0x7d, 0xa2, 0x86, 0xe0,
	0x03, 0x34, 0x54, 0x5d, 0xfb, 0x85, 0xeb, 0xa6, 0xef, 0x8e, 0xc0, 0xff, 0xd6, 0xe4, 0x74, 0x05,
	0x46, 0x75, 0x06, 0x3e, 0x42, 0x68, 0x4a, 0xe2, 0x17, 0x73, 0xc1, 0xab, 0x3c, 0x09, 0xbe, 0x37,
	0xfc, 0x57, 0x7c, 0x8a, 0x4f, 0xbc, 0x2e, 0xaa, 0xf1, 0xf0, 0x5b, 0x68, 0x68, 0x4f, 0xd7, 0xe5,
	0xb2, 0xa0, 0xc1, 0x0f, 0x47, 0x90, 0x6b, 0x1d, 0xc3, 0x0f, 0xd0, 0x20, 0xa3, 0x92, 0x5c, 0x92,
	0x79, 0x19, 0xfc, 0x78, 0xa4, 0x02, 0x1d, 0x1e, 0xee, 0x79, 0xb7, 0xcf, 0xac, 0xe6, 0x34, 0x97,
	0x62, 0x19, 0x79, 0x22, 0xfe, 0x48, 0xfb, 0xa5, 0x33, 0xaa, 0xd3, 0x51, 0xf9, 0xfd, 0x64, 0xc2,
	0xb9, 0xe3, 0xed, 0xce, 0x57, 0xca, 0xa8, 0xce, 0xc4, 0x8f, 0xd0, 0x56, 0x5c, 0x95, 0x92, 0x67,
	0x9f, 0x33, 0x9a, 0x26, 0x65, 0xf0, 0xb3, 0xf9, 0xe2, 0xca, 0xf2, 0x78, 0xa5, 0x8d, 0x1a, 0x54,
	0xfc, 0xa9, 0xea, 0x51, 0x90, 0x15, 0xb5, 0x28, 0x83, 0x5f, 0x8c, 0xe5, 0x6b, 0x2d, 0x4b, 0x50,
	0x9a, 0x70, 0xeb, 0xf4, 0xf0, 0x13, 0x34, 0x6a, 0x24, 0x83, 0xc7, 0x68, 0x4d, 0xef, 0xbe, 0x99,
	0x06, 0x7a, 0xa9, 0x8f, 0xf0, 0x15, 0x49, 0x2b, 0x37, 0x09, 0x8c, 0xf0, 0x71, 0xf7, 0x61, 0x27,
	0x7c, 0x8c, 0xc6, 0x6d, 0xef, 0xff, 0xcb, 0xfe, 0x11, 0x1a, 0xd6, 0xf2, 0xd2, 0xc4, 0x94, 0x4c,
	0x69, 0x6a, 0x8d, 0x8d, 0x70, 0xbb, 0x79, 0xf8, 0x57, 0x07, 0x0d, 0x6b, 0xd5, 0xc4, 0xf7, 0xd1,
	0x8e, 0x6d, 0xa3, 0xe5, 0x09, 0x2b, 0x8b, 0x94, 0xb8, 0x10, 0xda, 0xb0, 0x9e, 0x27, 0x33, 0x46,
	0xa4, 0x75, 0x07, 0x6b, 0xfc, 0x0e, 0xda, 0x8e, 0xc5, 0xb2, 0x90, 0xdc, 0x91, 0xed, 0x7c, 0x6b,
	0xa1, 0x30, 0xe9, 0x48, 0x3e, 0xaf, 0xd4, 0x21, 0xf3, 0x93, 0xce, 0xca, 0x3a, 0x82, 0x8c, 0x92,
	0xb2, 0x12, 0x34, 0xa3, 0xb9, 0x7c, 0x9e, 0x33, 0x37, 0xf3, 0xda, 0x70, 0xf8, 0xc7, 0x3a, 0x42,
	0xab, 0xc6, 0xc4, 0xe7, 0x68, 0x4c, 0x93, 0xca, 0xf4, 0xf3, 0x53, 0xa6, 0xca, 0x21, 0x74, 0xec,
	0x7a, 0x13, 0xef, 0xdd, 0xd2, 0xc7, 0x93, 0xd3, 0x16, 0x37, 0xba, 0x61, 0x8d, 0x2f, 0xd0, 0x2e,
	0xcd, 0x8a, 0x94, 0x2f, 0xf5, 0x27, 0x9d, 0xcb, 0x2e, 0xb8, 0x7c, 0xfb, 0x56, 0x97, 0x6d, 0x72,
	0x74, 0xd3, 0x3e, 0xfc, 0xad, 0x83, 0xc6, 0xed, 0x6f, 0xeb, 0x41, 0x5c, 0xc6, 0x0b, 0xce, 0xdd,
	0x9e, 0x59, 0x09, 0xbf, 0xa7, 0xaf, 0x15, 0xc1, 0x78, 0x02, 0x65, 0x1e, 0x1e, 0xee, 0xfa, 0xcf,
	0xc2, 0x64, 0x28, 0x48, 0x1e, 0x59, 0x82, 0x76, 0x91, 0xd0, 0xb9, 0xa0, 0xee, 0x4e, 0xb1, 0x12,
	0xde, 0x47, 0xc3, 0xa4, 0x76, 0x3d, 0x98, 0x72, 0xd7, 0xa1, 0xf0, 0xef, 0x0e, 0xda, 0xbd, 0x11,
	0x3a, 0x0e, 0xd0, 0x46, 0xcc, 0x33, 0xf5, 0x05, 0xd7, 0x01, 0x4e, 0x6c, 0x7b, 0xec, 0xde, 0xf0,
	0x88, 0x3f, 0xa8, 0xdd, 0x64, 0x6b, 0xad, 0xc0, 0xfd, 0xfc, 0x69, 0x5c, 0x6e, 0x92, 0xc9, 0xd4,
	0xf5, 0x82, 0x11, 0x74, 0x83, 0x09, 0xae, 0x40, 0xb3, 0xfb, 0xb0, 0xae, 0xd5, 0xa3, 0xff, 0x1f,
	0xf5, 0x08, 0x67, 0x68, 0xe0, 0x30, 0x3c, 0x51, 0xbd, 0x2a, 0x78, 0x06, 0x89, 0xbc, 0x7c, 0xcc,
	0x02, 0x4f, 0xdd, 0xab, 0x5d, 0xc9, 0x6d, 0xc9, 0x5f, 0xc6, 0x56, 0xac, 0xf0, 0x21, 0x1a, 0xf8,
	0x29, 0xaa, 0x42, 0x8e, 0x99, 0x74, 0x05, 0x83, 0xb5, 0xa9, 0x63, 0xa5, 0xcf, 0xb4, 0xad, 0x94,
	0x13, 0xc3, 0x5f, 0x3b, 0x68, 0xc3, 0x5e, 0x7d, 0x9a, 0x75, 0x4d, 0xa7, 0x25, 0x93, 0xd4, 0x55,
	0xdb, 0x8a, 0xba, 0x38, 0x34, 0x23, 0x2c, 0x75, 0xe7, 0x16, 0x04, 0xbd, 0x07, 0xc5, 0x82, 0xe7,
	0xf4, 0xcb, 0x2a, 0x9b, 0x52, 0x61, 0xb7, 0xbc, 0x0e, 0xa9, 0x9c, 0xfb, 0x25, 0x8f, 0x19, 0x49,
	0x55, 0x55, 0x9b, 0x53, 0xf7, 0x02, 0xe0, 0xcf, 0x62, 0x88, 0x23, 0xb2, 0xac, 0xf0, 0x39, 0x1a,
	0x35, 0x14, 0x3a, 0x19, 0xa9, 0xa7, 0xba, 0x4d, 0x46, 0xaf, 0xf5, 0xc1, 0xad, 0x4a, 0x2a, 0xe0,
	0xe9, 0x62, 0xe2, 0xf1, 0xb2, 0x0e, 0x54, 0x95, 0x88, 0xcf, 0x6c, 0x30, 0x46, 0x08, 0xbf, 0x45,
	0x3d, 0xb8, 0x4c, 0xc1, 0x1d, 0xf3, 0xcd, 0x04, 0x6b, 0x6d, 0x52, 0x66, 0x24, 0xf5, 0xb9, 0x81,
	0xa0, 0x3b, 0x39, 0xa3, 0x09, 0xab, 0x32, 0xd7, 0xc9, 0x46, 0x32, 0x73, 0x4d, 0xf8, 0x91, 0x61,
	0x04, 0x1d, 0x12, 0x17, 0x6c, 0xce, 0x72, 0x95, 0xa9, 0x69, 0x15, 0x2f, 0x87, 0xbf, 0x77, 0x50,
	0xdf, 0xbc, 0x16, 0x74, 0x81, 0x0b, 0xc1, 0x32, 0x22, 0x7c, 0x3b, 0x5b, 0x51, 0x3f, 0x76, 0x4a,
	0xaa, 0x5e, 0x1e, 0x09, 0xf1, 0x5b, 0xb4, 0x02, 0x20, 0x6c, 0x75, 0x51, 0xba, 0x87, 0x9a, 0x5e,
	0x6b, 0x8b, 0x05, 0x9b, 0x2f, 0x52, 0xf5, 0x93, 0x36, 0x98, 0x15, 0xa0, 0x5f, 0x00, 0x5e, 0xb8,
	0xd4, 0xa6, 0x26, 0xaa, 0x26, 0x18, 0xfe, 0xd3, 0x41, 0xbd, 0x0b, 0xf7, 0x62, 0x98, 0xf1, 0x34,
	0xe5, 0xd7, 0x54, 0x1c, 0xeb, 0xc2, 0x43, 0x7c, 0xa3, 0xa8, 0x09, 0xea, 0xd1, 0x6a, 0x00, 0x96,
	0xcf, 0x0d, 0xad, 0x0b, 0xb4, 0x16, 0x8a, 0xef, 0xaa, 0x97, 0x85, 0x3a, 0xc1, 0x9e, 0xb5, 0x06,
	0xac, 0x06, 0xa6, 0x9b, 0x47, 0xbd, 0xcd, 0x3c, 0x65, 0x1d, 0x28, 0x75, 0x48, 0x67, 0x58, 0xf0,
	0x52, 0x1a, 0x7d, 0x0f, 0xf4, 0x2b, 0x40, 0x47, 0x4c, 0xae, 0xd4, 0xf3, 0x4e, 0x3d, 0x91, 0xc0,
	0x06, 0x0e, 0x63, 0x37, 0x6a, 0x82, 0x4f, 0xd6, 0xbf, 0xea, 0x16, 0xd3, 0x69, 0x1f, 0x8e, 0xcd,
	0x83, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x71, 0x50, 0x57, 0xf0, 0x87, 0x0b, 0x00, 0x00,
}
